### ISSUE TITLE
Unhandled Exception: System.TypeLoadException:

### ISSUE THREAD

**Issue by AngelFreak** [linuxserver/docker-sonarr#142]
------------------------------

## Expected Behavior
Sonarr running, and being able to access the web inetrface

## Current Behavior
Sonarr starts but does not present the web interface, and the log file shows the following error over and over.
```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
```
## Steps to Reproduce

1. docker-compose up -d
2. add some shows
3. add some Torznab feeds
4. crash ?

## Environment
**OS:** Debian GNU/Linux 9.11 (stretch)
**CPU architecture:** x86_64
**How docker service was installed:**      

According to https://docs.docker.com/install/linux/docker-ce/debian/

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - UMASK_SET=022 #optional
    volumes:
      - sonarr-config:/config
      - sonarr-nfstvshows:/tv
      - sonarr-nfstorrent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'NzbDrone.Common.EnvironmentInfo.StartupContext:<Flags>k__BackingField' (8) due to: type 0x00 not handled in do_mono_metadata_parse_type on image /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
```

**Comment by j0nnymoe** [comment]
Where is `sonarr-config` pointing to?

**Comment by AngelFreak** [comment]
Sorry, forgot the last part of the compose file. Here is the full version.
```
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - UMASK_SET=022 #optional
    volumes:
      - sonarr-config:/config
      - sonarr-nfstvshows:/tv
      - sonarr-nfstorrent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

volumes:
  sonarr-config:
  sonarr-nfstvshows:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=x.x.x.x,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/x/x/x"
  sonarr-nfstorrent:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=x.x.x.x,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt//x/x"
networks:
  sonarr-net:
  traefik_proxy:
    external:
      name: traefik_proxy
```
