### ISSUE TITLE
Introduce healtcheck for image

### ISSUE THREAD

**Issue by stepanovdg** [linuxserver/docker-sonarr#158]
Requesting feature add healthcheck for instance. In order to restart in case of unhealthy.
Not sure maybe just usual curl host:port will be enough.(maybe you have better ideas.)

**Comment by thelamer** [comment]
We have been through this discussion many times before, for now as an organization we will not be implementing Healthchecks https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-546721863

**Comment by GAS85** [comment]
Simply add to your compose file:
```yaml

    healthcheck:
      test: curl -f http://localhost:8989/api/v3/health?apikey=<API KEY> || exit 1
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s
```
