### ISSUE TITLE
Sonarr gets connection refused when connecting to other services on localhost

### ISSUE THREAD

**Issue by PhantomGamers** [linuxserver/docker-sonarr#165]
I'm trying to setup sonarr to connect to a nzbhydra2 container and to the sabnzbd client on my host OS. The same exact connection settings work in the linuxserver radarr container, it's only sonarr that is having this problem.

## Environment
**OS:** Windows 10 x64 build 2004  
**CPU architecture:** x86_64      
**How docker service was installed:** Docker Desktop with WSL2 engine      

## Command used to create docker container (run/create/compose/screenshot)
```
sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ~/sonarr/data:/config
      - /mnt/d/TV:/tv
      - /mnt/d/SABnzbd/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
```

## Docker logs
[log.txt](https://github.com/linuxserver/docker-sonarr/files/4974954/log.txt)
