### ISSUE TITLE
Manual import failing with Error 50 - nfs volumes

### ISSUE THREAD

**Issue by konradbjk** [linuxserver/docker-sonarr#191]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Manual import of file from download/seeding folder to TV directory

## Current Behavior
Error 50

## Steps to Reproduce
Both seeding and media folders are different zfs datasets (hence different filesystems) and hardlinks will not work. 

I use NFS volumes for those and bind mount for Sonarr config. I downloaded one episode, it disappeared from the queue. I tried manual import, but I cannot even select the folder where the seeding volume is. Upon typing the path manually in the UI, we can see Error 50. 

Accessing the folder as abc user works like a charm.

Sonarr was able to import manually other episodes.

There is a quota neither on the datastore nor the user.

## Environment
**OS:** TrueNas 12.1, running Ubuntu VM as docker host
**CPU architecture:** x86_64
docker installed via snap, container created via portainer

## Docker logs
[_sonarr_logs.txt](https://github.com/linuxserver/docker-sonarr/files/6473428/_sonarr_logs.txt)

**Comment by j0nnymoe** [comment]
Don't install docker via snap as this puts in place extra restrictions which is likely causing you an issue (nor do we support this installation method). You need to install docker via the https://get.docker.com script.

**Comment by konradbjk** [comment]
thanks, @j0nnymoe I understand your concern, and I plan to migrate out of it, but that is not easy. I doubt this is the issue, as other dockers run just fine (i.e. qbittorrent).

Any other tips?

**Comment by Roxedus** [comment]
From what I came up with the amount of complexity in your system, something set the file in a state that neither part in your chain want to touch it.

**Comment by konradbjk** [comment]
@Roxedus  can you be more specific, what is complex here for you?
My chain?

**Comment by Roxedus** [comment]
It is not complex for me, its complex in general. Too many moving parts.

**Comment by konradbjk** [comment]
@j0nnymoe  I did recreate env using docker-ce still the same issue while manually importing files.

**Comment by j0nnymoe** [comment]
@konradbjk need you to provide docker run or compose info to help further

**Comment by konradbjk** [comment]
my compose:
```
version: "2"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1005
      - PGID=1002
      - TZ=Europe/Warsaw
    volumes:
      - /home/ubuntu/dockers/sonarr:/config
      - entertainment_tv:/media/tv
      - seeding_entertainment:/downloads/entertainment
    restart: always
    
volumes:
  seeding_entertainment:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.100.3,rw,hard,noatime,noacl,rsize=131072,wsize=131072,tcp
      device: ":/mnt/first/Completed_Downloads/entertainment"
      
  entertainment_tv:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.100.3,rw,hard,noatime,noacl,rsize=131072,wsize=131072,tcp
      device: ":/mnt/Entertainment/TV"

networks: 
  default: 
    external: 
      name: nat
```

volume `seeding_entertainment` is shared with qBittorrent, but each container is using a separate PUID.

**Comment by j0nnymoe** [comment]
But the same PGID?

Post your qbit compose too pleasr

**Comment by konradbjk** [comment]
@j0nnymoe PGID is the same, as 1002 is the group for all my services users
```
qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8080
    ports:
      - 58110:58100
    volumes:
      - qbittorrent_config:/config
      - seeding_entertainment:/downloads/entertainment
      - seeding_audiobooks:/downloads/audiobooks
      - seeding_ebooks:/downloads/ebooks
      - seeding_iso:/downloads/iso/
    logging:
      driver: gelf
      options:
        tag: qBittorrent
        gelf-address: "udp://REDACTED:12201"
    restart: always
```
