### ISSUE TITLE
Outdated MediaInfo for arm64

### ISSUE THREAD

**Issue by RBozydar** [linuxserver/docker-sonarr#202]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
MediaInfo should be the latest/last compatible version.
Currently in arm64 the version is 17.12 which is missing some crucial improvements with regards to handling Dolby Vision files. This causes Sonarr to incorrectly identify these files as not HDR.
```
root@b1e478c22aad:/# mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v17.12
```

## Current Behavior

```
docker exec -it sonar bash -c 'mediainfo --version'
```
Currently gives 
```
MediaInfo Command line, 
MediaInfoLib - v17.12
```

## Environment
**OS:** Ubuntu 21.10 (GNU/Linux 5.13.0-1011-raspi aarch64)
**CPU architecture:** arm64
**How docker service was installed:** official repository + docker-compose via PIP

## Command used to create docker container (run/create/compose/screenshot)

docker-compose
```
version: '3'

networks:
  proxy:
    external: true

services:
  sonarr:
    container_name: sonar
    image: ghcr.io/linuxserver/sonarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./configs/sonarr:/config
      - ./data/downloads:/downloads
      - /$MOUNT/:/data
    logging:
      driver: json-file
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.sonarr.rule=Host(`$REDACTED`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

```

I've just pulled the freshest image again and the version is the same.
I don't see MediaInfo as defined dependency in this repository's [build file](https://github.com/linuxserver/docker-sonarr/blob/master/Dockerfile.aarch64) nor in the base image, so not sure at which point it's getting pulled.

At least MediaInfo 21.03 is available for arm64, at least for Ubuntu 21.04 on RPi 4.

Happy to contribute a PR for this if someone could point me to the right place.
