### ISSUE TITLE
Cannot get sonarr docker-compose image to access specific volume

### ISSUE THREAD

**Issue by mariusberget92** [linuxserver/docker-sonarr#219]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Should be able to access with read and write to volume S1, but keep getting the error:
```
Invalid request Validation failed: 
 -- Path: Folder is not writable by user abc
```

## Current Behavior
I do get access to S2 and S3, both with the same permissions as S1. All three drives are mounted in `fstab` with exactly the same permissions. It's weird since I cannot access S1, but can access S2 and S3.

## Steps to Reproduce

1. Mount drives in `fstab`.
2. Setup docker and docker-compose.
3. Start the containers.
4. Try to add S1, S2 and S3 to sonarr. Only S2 and S3 accessible.

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:**
Docker was installed following [this](https://www.cloudbooklet.com/how-to-install-docker-on-ubuntu-22-04/) guide.
Docker-compose via apt.

## Command used to create docker container (run/create/compose/screenshot)
`docker-compose -d up`

Complete `docker-compose.yml`. Adding `fstab` below too.

```
version: '2.1'
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - /home/anoneemo/docker/heimdall:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    ports:
      - '80:80'
      - '443:443'
    restart: always
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - /home/anoneemo/docker/radarr:/config
      - /media/M1:/M1
      - /media/M2:/M2
      - /media/M3:/M3
      - /media/M4:/M4
      - /home/anoneemo/Downloads/rsync:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    ports:
      - '7878:7878'
    restart: always
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - /home/anoneemo/docker/sonarr:/config
      - /media/S1:/S1
      - /media/S2:/S2
      - /media/S3:/S3
      - /home/anoneemo/Downloads/rsync:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    ports:
      - '8989:8989'
    restart: always
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    volumes:
      - /home/anoneemo/docker/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    ports:
      - '9696:9696'
    restart: always
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - /home/anoneemo/docker/bazarr:/config
      - /media/M1:/M1
      - /media/M2:/M2
      - /media/M3:/M3
      - /media/M4:/M4
      - /media/S1:/S1
      - /media/S2:/S2
      - /media/S3:/S3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    ports:
      - '6767:6767'
    restart: always
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - /home/anoneemo/docker/overseerr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    ports:
      - '5055:5055'
    restart: always
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Oslo
    ports:
      - '${PORT:-8191}:8191'
    restart: always
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
    volumes:
      - /run/udev:/run/udev:ro
      - /home/anoneemo/docker/scrutiny/config:/opt/scrutiny/config
      - /home/anoneemo/docker/scrutiny/influxdb:/opt/scrutiny/influxdb
    ports:
      - '8080:8080'
      - '8086:8086'
    devices:
      - '/dev/sda'
      - '/dev/sdb'
      - '/dev/sdc'
      - '/dev/sdd'
      - '/dev/sde'
      - '/dev/sdf'
      - '/dev/sdg'
      - '/dev/sdh'
    restart: always
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    volumes:
      - /home/anoneemo/docker/plex:/config
      - /media/M1:/M1
      - /media/M2:/M2
      - /media/M3:/M3
      - /media/M4:/M4
      - /media/S1:/S1
      - /media/S2:/S2
      - /media/S3:/S3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - PLEX_CLAIM=claim-xT59astvoP5-LWm2Qozv
      - HOSTNAME="DARQNET"
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    restart: always
```

```
UUID=CEDEF25ADEF239F3 /media/M1          auto nosuid,nodev,nofail,x-gvfs-show,uid=anoneemo,gid=anoneemo 0 0
UUID=CC7E001B7E0000C6 /media/M2          auto nosuid,nodev,nofail,x-gvfs-show,uid=anoneemo,gid=anoneemo 0 0
UUID=CAF87B2DF87B16C3 /media/M3          auto nosuid,nodev,nofail,x-gvfs-show,uid=anoneemo,gid=anoneemo 0 0
UUID=7478FC7E78FC4082 /media/M4          auto nosuid,nodev,nofail,x-gvfs-show,uid=anoneemo,gid=anoneemo 0 0
UUID=08C0D533C0D527A8 /media/S2          auto nosuid,nodev,nofail,x-gvfs-show,uid=anoneemo,gid=anoneemo 0 0
UUID=E4D40A58D40A2D7C /media/S3          auto nosuid,nodev,nofail,x-gvfs-show,uid=anoneemo,gid=anoneemo 0 0
UUID=082F0A59162E00D0 /media/S1          auto nosuid,nodev,nofail,x-gvfs-show,uid=anoneemo,gid=anoneemo 0 0
```

Also worth mentioning; PUID and PGID is correct (1000).

Permissions for the drives:
```
drwxrwxrwx  1 anoneemo anoneemo 336K mai   19 14:30 M1
drwxrwxrwx  1 anoneemo anoneemo 160K mai   19 14:30 M2
drwxrwxrwx  1 anoneemo anoneemo  92K mai   19 14:30 M3
drwxrwxrwx  1 anoneemo anoneemo  44K mai   19 14:32 M4
drwxrwxrwx  1 anoneemo anoneemo  44K mai   18 09:23 S1
drwxrwxrwx  1 anoneemo anoneemo  12K mai   19 15:02 S2
drwxrwxrwx  1 anoneemo anoneemo  12K mai   19 15:02 S3
```
