### ISSUE TITLE
Slow file transfers out of container started recently

### ISSUE THREAD

**Issue by herkalurk** [linuxserver/docker-sonarr#222]
## Expected Behavior
Moving files between volumes attached to containers is limited by hardware

## Current Behavior
File moves using this container used to run around 70 MB/s, currently capping around 10 MB/s

## Steps to Reproduce
Sonarr sends downloads to sabnzbd, sonarr then manages files after download.  In previous releases there were no slow downs.

## Environment
**OS:** Centos 7
**CPU architecture:** x86_64
**How docker service was installed:** docker-ce repo

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/docker/sonarr:/config
      - /media/usenet:/media/usenet
      - /media/tv:/media/tv
    restart: unless-stopped
    ports:
      - 8989:8989
networks:
  default:
    external:
      name: sickly
```
