### ISSUE TITLE
[BUG] Sonarr caused very high constant host CPU usage

### ISSUE THREAD

**Issue by R8s6** [linuxserver/docker-sonarr#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lately I discovered that this docker would run with nearly full cpu usage inside a VM on a machine with Ryzen 3700x.

![](https://i.imgur.com/MMqXf82.png)

It used to be normal. 
I don't know when this abnormal cpu usage started, and currently it's running the latest version (as of 2023-01-04). 
```
About

Version 3.0.9.1549
Package Version 3.0.9.1549-ls171 by [linuxserver.io](https://linuxserver.io/) 
Mono Version 6.12.0.182
AppData directory /config
Startup directory /app/sonarr/bin
Mode Console
```

- Stopping the docker, VM CPU usage will go down immediately.
- Restarting the docker, and in about 1 minute, VM CPU usage will go up to full again.
- Tried pulling and restarting the docker, did not work, as it's already running the latest version (previously auto-updated by watchtower).

Anybody having a similar issue? Thanks!

### Expected Behavior

Minimum VM CPU usage (< 5%) for a modern CPU (Ryzen 3700x or better)

### Steps To Reproduce

1. In a ubuntu lts VM 22.04, 

2. run docker with the following docker-compose.yml

```
---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/xyz
      - UMASK=022
    volumes:
      - /home/abc/docker/sonarr/config:/config
      - /mnt/nas/media/Downloads:/media
    ports:
      - 8989:8989
    restart: unless-stopped
```

3. VM CPU shoots up to near 100%, this pulse would last minutes, then CPU temporarily drops down to idel for a few seconds before shooting up to near 100% again. This whole process would last at least hours (before I stop this docker).

### Environment

```markdown
- OS: Ubuntu VM, LTS 22.04
- How docker service was installed: Following the official docker-compose installation guide.
- Host CPU: AMD Ryzen 3700x
- Hypervisor: qemu + kvm + virt-manager on Archlinux
```

### CPU architecture

x86-64

### Docker creation

`docker-compose.yml`:

```
---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/xyz
      - UMASK=022
    volumes:
      - /home/abc/docker/sonarr/config:/config
      - /mnt/nas/media/Downloads:/media
    ports:
      - 8989:8989
    restart: unless-stopped
```

Then `docker-compose up -d`
