### ISSUE TITLE
Workaround for not able to hardlink content from /downloads

### ISSUE THREAD

**Issue by michaelarnauts** [linuxserver/docker-sonarr#34]
Sonarr can't use hardlinks to put files from `/download` to `/tv`, since they are on a different docker volume. This causes extensive disk IO, and drive space duplication, even though they are physical on the same disk.

A solution for this could be to map a higher folder to docker, and work with symlinks to that folder inside docker.

Example:

# Before:
```yaml
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - "127.0.0.1:8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /etc/sonarr:/config
      - /mnt/data/tv:/tv
      - /mnt/data/torrents/tv:/downloads
```

# After:
```yaml
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - "127.0.0.1:8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /etc/sonarr:/config
      - /mnt/data:/data
```

And then have the container create a symlink from `/data/tv` to `/tv`, and from `/data/torrents/tv` to `/downloads`.

```sh
$ ln -s /data/tv /tv
$ ln -s /data/torrents/tv / downloads
```

This could speed up the final processing of the downloaded content a lot.
