### ISSUE TITLE
Connection refused with torznab

### ISSUE THREAD

**Issue by Oscarteg** [linuxserver/docker-sonarr#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
I am trying to connect my jackett docker container from linuxserver to sonarr. When I input the settings and click test it says it works but when I try to download a episode I does not download the torrent to my blackhole directory.  

I am using an Ubuntu 16.04 server with `Docker version 17.03.0-ce, build 60ccb22`. 

This is a part of my docker-compose to setup sonarr and jackett. 
```
sonarr: 
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - 8989:8989
    volumes:
      - sonarr:/config
      - ${TORRENTS_DIR}:/downloads
      - ${SHOWS_DIR}:/tv
    restart: always

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    environment:
      PGID: ${UID}
      PUID: ${UID}
    ports: 
     - 9117:9117
    volumes:
      - jackett:/home/jackett/.config/Jackett
      - ${TORRENTS_DIR}/auto-add:/downloads
    restart: always

```

These are my settings in sonarr. 
![image](https://cloud.githubusercontent.com/assets/8656565/23812667/c4f0bc28-05db-11e7-89af-062c0b90cb0b.png)

This is the error in my log.

```
Downloading torrent file for episode 'Atlanta S01E05 Nobody Beats the Biebs 720p WEB-DL DD5 1 H 264-Oosh' failed (http://localhost:9117/dl/torrentday/t4ufjjsbl2lhn7w4ji6939j4zrufwk9g?path=aHR0cHM6Ly90b3JyZW50ZGF5Lml0L2Rvd25sb2FkLnBocC8xOTM4NTgzL0F0bGFudGEgUzAxRTA1IE5vYm9keSBCZWF0cyB0aGUgQmllYnMgNzIwcCBXRUItREwgREQ1LjEgSC4yNjQtT29zaC50b3JyZW500&file=Atlanta+S01E05+Nobody+Beats+the+Biebs+720p+WEB-DL+DD5+1+H+264-Oosh.torrent): Error: ConnectFailure (Connection refused)

System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x4075fcd0 + 0x0019f> in <filename unknown>:0 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) <0x4075e930 + 0x0058f> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x4075d9b0 + 0x001a3> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () <0x407593c0 + 0x00053> in <filename unknown>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fb] in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:63 
```
