### ISSUE TITLE
"Access Denied" even when using GUID / PGID

### ISSUE THREAD

**Issue by marksie1988** [linuxserver/docker-sonarr#73]
Im using a centos7 VM with docker installed, it runs under root and have set the docker compose as below: 
```
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    depends_on:
      - proxy
    restart: always
    volumes:
      - sonarr_conf:/config:rw
      - downloads:/downloads:rw
      - sonarr_tv:/tv:rw
    ports:
      - 8989:8989
    environment:
      - PGID=0
      - GUID=0
      - TZ=Europe/London
volumes:
  sonarr_conf:
    driver_opts:
      type: none
      device: /mnt/nfs/dockerfiles/sonarr/conf
      o: bind
  downloads:
    driver_opts:
      type: none
      device: /mnt/nfs/deluge/downloads
      o: bind
  sonarr_tv:
    driver_opts:
      type: none
      device: /mnt/nfs/media/tv
      o: bind

```

when a download is detected and it tries to copy it to the tv folder it fails saying access denied, it seems to be trying to copy it over as the user "abc" rather than root as i would expect it to. 

Im now lost as to why this is happening as i thought the whole point in GUID and PGID was to stop this happening. 

the mounts are NFS, Downloads is an export on another centos7 vm and TV is a FreeNAS NFS Share.
