### ISSUE TITLE
Import failed, path does not exist or is not accessible by Sonarr

### ISSUE THREAD

**Issue by parrappappa** [linuxserver/docker-sonarr#85]
I keep getting the following error:

```
[Error] DownloadedEpisodesImportService: Import failed, path does not exist or is not accessible by Sonarr: /config/Downloads/complete/some.folder/ 
```

I am using *Linuxserver.io version:- 168 Build-date:- December-14-2018-23:20:18-UTC*

Made the following mapping

```
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /home/me/opt/media/config/sonarr/:/config 
      - /home/me/videos/series/:/tv 
      - /home/me/opt/media/downloads/complete:/downloads 
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "8989:8989"
```

Should it not use `/downloads` which is mapped to ` /home/me/opt/media/downloads/complete`

**Comment by j0nnymoe** [comment]
Make sure all containers are using the same `/downloads` mount or use the remote mapping feature in sonarr.

**Comment by parrappappa** [comment]
My sabnzbd is using the same:

```
version: "3.7"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    volumes:
      - /home/me/opt/usenet/config/sabnzbd:/config 
      - /home/me/opt/usenet/downloads/complete:/downloads 
      - /home/me/opt/usenet/downloads/incomplete:/incomplete-downloads 
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "8980:8080" 
      - "8933:9090"
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /home/me/opt/usenet/config/sonarr/:/config 
      - /home/me/videos/series/:/tv 
      - /home/me/opt/usenet/downloads/complete:/downloads 
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "8989:8989"
```
Why is sonarr trying to access `/config/Downloads/complete/` and not just `/downloads'?

**Comment by j0nnymoe** [comment]
Because that's what sab is telling sonarr. Take the complete stuff off the paths.

**Comment by parrappappa** [comment]
I still have the problem with the configuration below. (BTW if there is a better platform to ask these kind of questions i am happy to post it thete, as i am aware this is for issues. Thanks for your help)

```
version: "3.7"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    volumes:
      - /home/me/opt/media/config/sabnzbd:/config 
      - /home/me/opt/media/downloads:/downloads 
      - /home/me/opt/media/downloads/incomplete:/incomplete-downloads 
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "8980:8080" 
      - "8933:9090"
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /home/me/opt/media/config/sonarr/:/config 
      - /home/me/videos/series/:/tv 
      - /home/me/opt/media/downloads:/downloads 
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "8989:8989"
      
      

      
```
