### ISSUE TITLE
Issue with mono keypairs HTTP 500 error signalr

### ISSUE THREAD

**Issue by jazo10** [linuxserver/docker-sonarr#88]
I've been having some issues with the web UI not refreshing.
The issue was caused by signalr returning a 500 error when trying to negotiate the authentication and create a WebSocket connection.

docker-composer script
```
  sonarr:
    restart: always
    image: 'linuxserver/sonarr:latest'
    volumes:
      - '.\volumes\sonarr\config:/config'
      - '.\volumes\common\downloads\:/mnt/usr/downloads'
    ports:
      - '8989:8989'
    environment:
      - XDG_CONFIG_HOME=/tmp/xdg
      - PGID=1001
      - PUID=1001
      - TZ=australia/melbourne
```
OS: Windows 10

After a lot of research and some info from https://github.com/linuxserver/docker-sonarr/issues/3
it looks like there was some permission issues resolving to the windows config volume when trying to save keypairs for mono. Setting this to a container path solves the issue, and shouldn't be impacted by the container being rebuilt.

i was able to resolve this by setting the environment variable to `XDG_CONFIG_HOME=/tmp/xdg`.

**Suggestion**
Might be worth documenting the XDG_CONFIG_HOME var in the readme to help with anyone else who gets this issue in the future.
